name: ci
on:
  push:
    branches: 
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs==1.1.2
          pip install mkdocs-material mkdocs-macros-plugin

      # First, build the site
      - name: Build MkDocs Site
        run: mkdocs build  # This generates the ./site directory

      # Deploy separately
      - name: Deploy MkDocs
        run: |
          mkdocs gh-deploy --force --clean --remote-branch gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages Deployment
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site  # The `site/` directory now exists

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3



# name: Deploy Mkdocs Site

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#     paths:
#       - "docs/**"
#   pull_request:
#     branches: [ "main" ]
#     paths:
#       - "docs/**"

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.8"

#       - name: Install dependencies
#         run: |
#           pip install mkdocs-material mkdocs-macros-plugin

#       - name: Build MkDocs
#         run: |
#           mkdocs build

#       - name: Deploy MkDocs
#         run: |
#           mkdocs gh-deploy --force --clean --remote-branch gh-pages
#           git push origin gh-pages --force
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}